#!/usr/bin/python3
import random
number = random.randint(-1000, 1000)
last_digit = int(repr(number)[-1])
if last_digit > 5:
    print(f"Last digit of %d is {repr(last_digit)} and is greater than 5" % number)
elif last_digit == 0:
    print(f"Last digit of %d is {repr(last_digit)} and is 0" % number)
elif last_digit < 6 and number != 0:
    print(f"Last digit of %d is {repr(last_digit)} and is less than 6 and not 0" % number)
